server:
  port: 8080
spring:
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: default
      password: password
  data:
    couchbase:
      auto-index: true
  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389
logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.couchbase: DEBUG
